#!/usr/bin/env bash
# installs and sets NGINX to listen at port 80
sudo apt-get update -y
# Install engineX
sudo apt-get install nginx -y
# set NGINX to the port 80
sudo ufw allow "Nginx HTTP"
# let NGINX listen on port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# sudo echo "Hello, World!" >  /var/www/html/index.html
echo "Hello, World!" | sudo /var/www/html/index.html
sudo sed -i '/^#.*root/a \\t\tindex index.html;' /etc/nginx/sites-available/default
sudo service nginx start