#!/usr/bin/env bash
# Install engineX
sudo apt-get install nginx -y
# set NGINX to the port 80
sudo ufw allow "Nginx HTTP"
# let NGINX listen on port 80
sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo sed -i 's/8080/80/' /etc/nginx/sites-available/default
sudo service nginx start
echo "Hello, World!" | sudo tee /var/www/html/index.html
