#!/usr/bin/env bash
# Process and PID file
# su touch /var/run/myscript.pid
# $BASHPID > "/var/run/myscript.pid"

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo \"I hate the kill command\"" SIGTERM
done
trap 'echo "Y U no love me?!"' SIGINT
