#!/usr/bin/env bash
# Process and PID file
echo $$ > sudo tee "/var/run/myscript.pid"

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo \"I hate the kill command\"; sudo rm -rf /var/run/myscript.pid; exit" SIGTERM SIGQUIT
    trap 'echo "Y U no love me?!"' SIGINT
done
