#!/usr/bin/env bash
# Scripts that displays Hi on the 9th iteration using while loop

i=1
while((i<=10))
do
    if [ $i -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
