#!/usr/bin/env bash
# # script that returns the active IPV4 IP of the machine it is being runned
# ip a | grep -Eo "\b([0-9]{1,3}\.){1,3}[0-9]{1,3}\b"
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
